name: Pull Data to Server

on:
  push:
    branches: master
jobs:
  phpunit:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - name: Checkout code
        working-directory: /var/www/html/tacticaledge-movie-app/frontend/
        run: |
          echo "tacticaledge-movie-app-frontend"
          sudo git stash save --include-untracked "Custom message for my stash"
          sudo git pull
          npm i -f
          npm run build 
          cd /var/www/html/tacticaledge-movie-app/backend/
          npm i -f
          pm2 restart 0
