name: Pull Data to Server

on:
  push:
    branches: master
jobs:
  phpunit:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [v21.5.0]
    steps:
      - uses: actions/checkout@v1
      - name: Checkout code
        working-directory: /var/www/html/tacticaledge-movie-app/frontend/
        run: |
          echo "tacticaledge-movie-app-frontend"
          sudo git stash save --include-untracked "Custom message for my stash"
          sudo git pull
          npm i -f
          npm run build 
