name: Pull Data and Build

on:
  push:
    branches:
      - master

jobs:
  pull_and_build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Git Pull in Custom Folder
        run: |
          echo "tacticaledge-movie-app-frontend"
          cd /var/www/html/tacticaledge-movie-app/
          sudo git stash save --include-untracked "Custom message for my stash"
          sudo git pull

      - name: Install Dependencies and Build
        working-directory: /var/www/html/tacticaledge-movie-app/frontend/
        run: |
          sudo su 
          sudo npm install
          sudo npm run build
